pipeline {
	agent none
	options { skipDefaultCheckout(true) }
	stages {
		stage('Build and Test') {
			agent {
				docker {
					image '8-jdk-alpine'
					args '-v /var/jenkins_home/workspace/BalTo/S05P13D103:/var/jenkins_home/workspace/BalTo/S05P13D103'
				}
			}
			options { skipDefaultCheckout(false) }
			steps {
				sh '/var/jenkins_home/workspace/BalTo/S05P13D103/backend/gradlew clean build'
			}
		}
		stage('Docker build') {
			agent any
			steps {
				sh 'docker build -t frontend:latest /var/jenkins_home/workspace/BalTo/S05P13D103/frontend'
				sh 'docker build -t backend:latest /var/jenkins_home/workspace/BalTo/S05P13D103/backend'
			}
		}
	}
}




