pipeline {
	agent none
	options { skipDefaultCheckout(false) }

	stages {

		stage('Docker build') {
      agent any
			steps {
				sh 'docker build -t frontend:latest /var/jenkins_home/workspace/BalTo/frontend'
				sh 'docker build -t backend:latest /var/jenkins_home/workspace/BalTo/backend'
			}
		}
		stage('Docker run') {
			agent any
			steps {
				sh 'docker ps -f name=frontend -q | xargs --no-run-if-empty docker container stop'
				sh 'docker ps -f name=backend -q | xargs --no-run-if-empty docker container stop'

				sh 'docker container ls -a -f name=frontend -q | xargs -r docker container rm'
				sh 'docker container ls -a -f name=backend -q | xargs -r docker container rm'

				sh 'docker images prune'

				sh 'docker run -d --name frontend -p 8080:8080 frontend:latest'
				sh 'docker run -d --name backend -p 8443:8080 backend:latest'
			}
		}
	}
}