pipeline {
	agent none
	options { skipDefaultCheckout(true) }

	stages {

		stage('Docker build') {
		  agent any
			steps {
				sh 'docker build -t frontend:lates frontend/Dockerfile'
				sh 'docker build -t backend:latest backend/Dockerfile'
			}
		}
	}
}